### ISSUE TITLE
Indicate that the tool works for Datastore backups too

### ISSUE THREAD

**Issue by mkondratek** [Venryx/firestore-leveldb-tools#2]
Hi! 

First of all, thank you a lot @Venryx for providing this tool. I spent a couple of hours looking for a way to convert the Datastore backup to JSON. I came across [leveldb-json repo](https://github.com/nisaacson/leveldb-json) (which works with node 0.10.25 and npm 1.3.24, so it is quite outdated :rofl: ) and [this gist](https://gist.github.com/mkorthof/412e3cb64785c4f136bbb7f6a9d3a71c) but none of them worked for me.

## Issue

The repo name and README do not reflect the full possible application of the tool. In my case, I am working with Datastore backup. What about mentioning that the tool works for Datastore backups too? I think that it would help people like me searching for it and clearly understand what it can do.

**Comment by Venryx** [comment]
Done.

Thanks for the suggestion. :)
